compuproveedores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('custom_admin/', include('custom_admin.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, re_path

from .views import (
    actualizar_datos, redireccion, index, en_construccion, productos, productos_servicios,
    directorio, contacto, contactanos, bolsa_trabajo, distribuidores,
    registro_distribuidor,
    encuesta, solicitar_credito_datos, solicitar_credito,
    seleccionar, nosotros, solicitar_credito_pdf, soluciones, solucion,
    distribuidor_pdf,
    ver_block, promociones, empresas, rastreo, nuestra_historia, resultado_bolsa_trabajo,
    mundo_tecnologia, certificaciones, concretar_cita,
    validate_contactanos, terminos_condiciones_garantias,
    soluciones_tecnologicas, aviso_privacidad
)

urlpatterns = [
    #     path('', redireccion, name="redireccion"),
    path('', index, name="index"),
    path('en_construccion/', en_construccion, name="en_construccion"),
    path('productos/', productos, name="productos"),
    path('productos_servicios/', productos_servicios, name="productos_servicios"),
    path('directorio/', directorio, name="directorio"),

    path('contacto/', contacto, name="contacto"),
    path('contactanos/', contactanos, name="contactanos"),
    path('bolsa_trabajo/', bolsa_trabajo, name="bolsa_trabajo"),
    path('distribuidores/', distribuidores, name="distribuidores"),
    path('registro_distribuidor/', registro_distribuidor,
         {'distribuidor': True}, name="registro_distribuidor"),
    re_path(r'^modificacion_distribuidor/(.+)/(.+)/$', registro_distribuidor,
            {'distribuidor': True}, name="modificacion_distribuidor"),
    re_path(r'^modificacion_empresa/(.+)/(.+)/$', registro_distribuidor,
            {'distribuidor': False}, name="modificacion_empresa"),
    path('encuesta/', encuesta, name="encuesta"),
    path('solicitar_credito_distribuidor/', solicitar_credito_datos,
         {'es_dis': True}, name="solicitar_credito_distribuidor_datos"),
    re_path(r'^solicitar_credito_distribuidor/(.*)/$', solicitar_credito,
            {'distribuidor': True}, name="solicitar_credito_distribuidor"),

    path('seleccionar/', seleccionar, name="seleccionar"),
    path('nosotros/', nosotros, name="nosotros"),
    path('soluciones/', soluciones, name="soluciones"),
    re_path(r'^solucion/(.*)/$', solucion, name="solucion"),

    path('distribuidor_pdf/(\d+)/$', distribuidor_pdf,
         {'distribuidor': True}, 'distribuidor_pdf'),
    path('alta_distribuidor_pdf/(\d+)/$', distribuidor_pdf,
         {'distribuidor': True, 'actualizacion': False}, 'distribuidor_pdf_alta'),
    path('distribuidores/actualizar_datos/', actualizar_datos,
         {'es_distribuidor': True}, 'actualizar_datos_distribuidor'),
    path('empresas/actualizar_datos/', actualizar_datos,
         {'es_distribuidor': False}, 'actualizar_datos_empresa'),
    path('empresa_pdf/(\d+)/$', distribuidor_pdf,
         {'distribuidor': False}, 'empresa_pdf'),
    path('empresa_pdf_alta/(\d+)/$', distribuidor_pdf,
         {'distribuidor': False, 'actualizacion': False}, 'empresa_pdf_alta'),

    path('solicitar_credito_dis_pdf/(\d+)/$', solicitar_credito_pdf,
         {'distribuidor': True}, 'solicitar_credito_dis_pdf'),
    path('solicitar_credito_cli_pdf/(\d+)/$', solicitar_credito_pdf,
         {'distribuidor': False}, 'solicitar_credito_cli_pdf'),

    path('ver_block/', ver_block, name="ver_block"),

    path('promociones/', promociones, name="promociones"),

    path('empresas/', empresas, name="empresas"),
    path('registro_empresa/', registro_distribuidor,
         {'distribuidor': False}, name="registro_empresa"),
    re_path(r'^solicitar_credito_empresa/(.*)/$', solicitar_credito,
            {'distribuidor': False}, "solicitar_credito_empresa"),
    path('solicitar_credito_empresa/', solicitar_credito_datos,
         {'es_dis': False}, "solicitar_credito_empresa_datos"),

    path('garantia/', rastreo, {'tipo': 0}, name="garantia"),
    path('servicio_tecnico/', rastreo, {'tipo': 1}, name="servicio"),
    path('nuestra_historia/', nuestra_historia, name="nuestra_historia"),
    path('resultado_bolsa_trabajo/', resultado_bolsa_trabajo,
         name="resultado_bolsa_trabajo"),

    path('mundo_tecnologia/', mundo_tecnologia, name="mundo_tecnologia"),
    path('certificaciones/', certificaciones, name="certificaciones"),
    re_path(r'^concretar_cita/(.+)/$', concretar_cita, name="concretar_cita"),

    path('validate_contactanos/', validate_contactanos,
         name="validate_contactanos"),
    path('terminos_condiciones_garantias/', terminos_condiciones_garantias,
         name="terminos_condiciones_garantias"),

    # Fijas
    re_path(r'^soluciones_tecnologicas/(.+)/$',
            soluciones_tecnologicas, name="soluciones_tecnologicas"),
    path('aviso_privacidad/', aviso_privacidad, name="aviso_privacidad"),
]

core/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from django.forms.models import modelformset_factory
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from annoying.functions import get_object_or_None
from core.preguntas_respuestas import *
from django.forms.utils import ErrorList
class CalendarWidget(forms.DateInput):
    def __init__(self, attrs={}):
        attrs['class'] = 'has_datepicker'
        attrs['size'] = '8'
        
        super(CalendarWidget, self).__init__(attrs=attrs)

class CalendarDateField(forms.DateField):
    def __init__(self, *args, **kwargs):
        super(CalendarDateField, self).__init__(
            input_formats=('%d/%m/%y', '%d/%m/%Y', ), 
            widget=CalendarWidget,
            *args, **kwargs
        )

class ListaForm(forms.ModelForm):
    class Meta:
        model = Lista
        exclude = ()
    fecha_vencimiento = CalendarDateField(required=False)
    

class ConcretarCitaForm(forms.ModelForm):
    class Meta:
        model = ConcretarCita
        exclude = ('desactivar_email', 'created', 'solucion')
        #fields=("texto", )
        
        
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris',  }) ) 
    telefono = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris telefono_lada', }), label=("Teléfono")) 
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label=("E-mail") ) 
    empresa = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label=("Empresa"), required=False) 
    comentarios = forms.CharField(widget=forms.Textarea(attrs={'class':'input_gris_comentarios', },), required=True)

    def __init__(self, *args, **kwargs):
        super(ConcretarCitaForm, self).__init__(*args, **kwargs)

    

class SolicitudTrabajoForm(forms.ModelForm):
    class Meta:
        model = SolicitudTrabajo
        exclude = ('desactivar_email', 'created', 'apellido', 'vacante' )
        #fields=("texto", )
        
        
    curriculum = forms.FileField(widget=forms.FileInput(attrs={}), label="", )
    
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris',  }) ) 
    telefono = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris telefono_lada', }), label=("Teléfono (Lada)")) 
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label=("Correo Electrónico") ) 
    puesto = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label=("Puesto"), required=False) 
    aspiracion = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label="Sueldo", required=False ) 

    def __init__(self, *args, **kwargs):
        super(SolicitudTrabajoForm, self).__init__(*args, **kwargs)

        
class MensajeContactoForm(forms.ModelForm):
    class Meta:
        model = MensajeContacto
        exclude = ('desactivar_email', )
        
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris',  }) ) 
    telefono = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris telefono_lada', }), label=("Teléfono")) 
    empresa = forms.CharField(widget=forms.TextInput(attrs={'class':'input_gris', }), label=("Empresa") ) 
    comentarios = forms.CharField(widget=forms.Textarea(attrs={'class':'input_gris_comentarios', },), required=True)
    
class ObtenerBitacoraForm(forms.Form):
    
    guia_garantia = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input_gris'}), max_length=7, required=False)
    guia_servicio = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input_gris'}), max_length=7, required=False)
    
    def clean_guia_garantia(self):
        garantia = self.data.get("garantia")
        guia = self.cleaned_data['guia_garantia']
        
        if garantia:
            if guia:
                bitacora = get_object_or_None(Bitacora, tipo=0, guia=guia)
                if not bitacora:
                    raise forms.ValidationError("Código Inválido")
            else:
                raise forms.ValidationError("Este campo es obligatorio")
        return guia

    def clean_guia_servicio(self):
        servicio = self.data.get("servicio")
        guia = self.cleaned_data['guia_servicio']
        
        if servicio:
            if guia:
                bitacora = get_object_or_None(Bitacora, tipo=1, guia=guia)
                if not bitacora:
                    raise forms.ValidationError("Código Inválido")
            else:
                raise forms.ValidationError("Este campo es obligatorio")
        return guia
        

class DistribuidorForm(forms.ModelForm):
    class Meta:
        model = Distribuidor
        exclude = ('clave_modificacion',
                   'distribuidor',
                   'fecha_clave',
                   'vendedor',
                   'dias_credito',
                   'limite_credito',
                   'observaciones', 
                   'antiguedad_comerciales',
                   'dias_credito_comerciales',
                   'credito_comerciales',
                   'forma_pago_comerciales',
                   'desactivar_email',
                   'no_clientes_interno',
                   'clasificacion_interno',
                   'no_vendedor_interno',
                   'dias_credito_interno',
                   'limite_credito_interno',
                   'encargado_entregas_pago',
                   'pagina_web_pago', 
                   'titular_cuenta',
                   'banco',
                   'ejecutivo',
                   'no_cuenta',
                   'telefono_bancarias',
                   'promedio_mensual',
                   'antiguedad_bancarias',
                   'tipo_distribuidor',
                   'vendedor_interno',
                   )



    SUCURSALES = (
          ("", '---------'),
          (1, 'TIJUANA'),
          (2, 'HERMOSILLO'),
          (3, 'CULIACAN'),
          (4, 'AGUASCALIENTES'),
    )
    sucursal = forms.ChoiceField(choices=SUCURSALES, required=True) 

    def clean(self):
        p_required_fields = [
    
    "pagos_banco_1",
    "pagos_no_cuenta_1",
    "pagos_banco_2",
    "pagos_no_cuenta_2",
    "contacto_revision_facturas",
    "dias_revision",
    "horario_revision",
    "telefono_revision",
    "doc_revision",    
    "encargado_departamento_pago",
    "email_pago",
    "telefono_pago",
    "dias_pago",
    "horario_pago",
    "correo_envio_facturas",
    "documento_revision_pago",
    "nombre_empresa",
    "ciudad_comerciales",
    "estado_comerciales",
    "atencion_comerciales",
    "telefono_comerciales",
    "nombre_empresa_2",
    "ciudad_comerciales_2",
    "estado_comerciales_2",
    "atencion_comerciales_2",
    "telefono_comerciales_2",
    "nombre_empresa_3",
    "ciudad_comerciales_3",
    "estado_comerciales_3",
    "atencion_comerciales_3",
    "telefono_comerciales_3",
    
    
]
    
        cleaned_data = self.cleaned_data
        for f in p_required_fields:
            if not cleaned_data["no_usar_datos_bancarios"] and not cleaned_data[f]:
                self._errors[f] = ErrorList(["Campo requerido."])
                
        return cleaned_data
        
        
    def __init__(self, *args, **kwargs):
        super(DistribuidorForm, self).__init__(*args, **kwargs)
  
                                    

class SolicitarCreditoForm(forms.ModelForm):
    class Meta:
        model = SolicitarCredito
        exclude = (
            'created', 
            'distribuidor',
            'rc_antiguedad_1',
            'rc_dias_credito_1',
            'monto_credito_1',
            'forma_pago_1',
            'rc_antiguedad_2',
            'rc_dias_credito_2',
            'monto_credito_2',
            'forma_pago_2',
            'rc_antiguedad_3',
            'rc_dias_credito_3',
            'monto_credito_3',
            'forma_pago_3',
            'razon_social',
            'dist',
        )



class BuscarVacanteForm(forms.Form):
    
    CIUDADES = (
                (0, "Todas"),
                ('Matriz Hermosillo', 'Matriz Hermosillo'),
                ('Sucursal Tijuana', 'Sucursal Tijuana'),
                ('Sucursal Culiacan', 'Sucursal Culiacan'),
                ('Sucursal Aguascalientes', 'Sucursal Aguascalientes'),
    )
    q = forms.CharField(max_length="250", required=False, widget=forms.TextInput(attrs={'size':'30', 'class':"input_gris"}))
    ciudad = forms.ChoiceField(choices=CIUDADES)
class CurriculumForm(forms.ModelForm):
    class Meta:
        model = SolicitudTrabajo
        fields = ('curriculum', )
        
class ContactanosForm(forms.Form):
    
    serie = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'size':'8', 'class':"input_gris"}))
    folio = forms.IntegerField(widget=forms.TextInput(attrs={'size':'8', 'class':"input_gris"}))   
    
    
    
    def clean_serie(self):
        serie = self.cleaned_data['serie'].upper()
        serie_correcta = False
        series = ["H", "CUL", "AGS", "TIJ"] 
        
        for s in series:
            if s == serie:
                serie_correcta = True
        
        if not serie_correcta:
            raise forms.ValidationError('La serie es incorrecta')

        return serie

class EmailForm(forms.Form):
    
    nombre = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'size':'30', 'style':"color:#BCBCBC; "}))
    destinatario = forms.EmailField(widget=forms.TextInput(attrs={'size':'30', 'style':"color:#BCBCBC;"}))
    
    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        self.initial['nombre'] = "Tu nombre"
        self.initial['destinatario'] = "Correo electrónico"
        



class EncuestaSatisfaccionForm(forms.ModelForm):
    class Meta:
        model = EncuestaSatisfaccion
        exclude = ('pregunta_6', 'pregunta_7')
        
    
    

templates/soluciones_tecnologicas/active_directory.html
{% extends "soluciones_tecnologicas/base.html" %}
{% load static %}

{% block l_width %}360{% endblock %}

{% block soluciones_title %}
    ACTIVE DIRECTORY
{% endblock %}

{% block soluciones_text %}

<div class="columna_l">
<p class="bold">¿Está alineado el esquema organizacional de su empresa  respecto a las políticas y privilegios de Tecnologías de Información (IT por sus siglas en inglés)?</p>
<p>En Compuproveedores le ofrecemos un medio para organizar, administrar y controlar de forma centralizada el acceso de los usuarios y aplicaciones a los recursos existentes en su red.</p>

<p class="beneficios">Beneficios:</p>
        
<ul>
    <li>Incrementa la productividad de los usuarios mediante la creación de perfiles y privilegios en base a su Organigrama Empresarial.</li>
    <li>Proporciona control, flexibilidad, disponibilidad, seguridad y confiabilidad en su infraestructura de operaciones e información.</li>
    <li>Plataforma de integración con diversas aplicaciones, soluciones flexibles y sistemas conectados.</li>
    <li>Experiencias valiosas para administración de usuarios y equipos, mejoras fundamentales en el rendimiento de sus recursos de IT. </li>
</ul>

<div style="height:10px;"></div>
<div style="text-align:right;" class="demo">Contamos con Demo.</div>
</div>

<div class="columna_r">
    <div class="left">
        <img src="/site_media/compu/images/{{ id }}.png">
    </div>    
</div>

{% endblock %}

templates/soluciones_tecnologicas/aulas_interactivas.html
{% extends "soluciones_tecnologicas/base.html" %}

{% block l_width %}360{% endblock %}

{% block soluciones_title %}
    AULAS INTERACTIVAS
{% endblock %}

{% block soluciones_text %}

<div class="columna_l" style="width:300px;">
    <p class="bold">¿Le gustaría contar con tecnología en sus aulas y aprovechar los contenidos digitales?</p>

    <p>Compuproveedores puede ayudarle a crear un aula interactiva; que es un Centro de Tecnología Educativa el cual pretende transformar el proceso de aprendizaje con la más avanzada tecnología en enseñanza y equipos didácticos.

    Le ofrecemos esta solución en dos modalidades:
    Diseño de aulas Interactivas como proyecto. 
    Conversión de salones de cómputo ya existentes en
    aulas interactivas.
    </p>

    <p class="beneficios">Beneficios:</p>
            
    <ul>
        <li>Los estudiantes muestran mayor motivación y se alienta a su participación en clase.</li>
        <li>Permite a los profesores, expositores, conferencistas utilizar los recursos multimedia y de Internet creando mayor interés entre los asistentes.</li>
        <li>Integración con librerías de Microsoft Office.</li>
    </ul>
    <div style="height:10px;"></div>
    <div style="text-align:right;" class="demo">Contamos con Demo.</div>
</div>

<div class="columna_r" style="width:290px;">
    <ul>
        <li>Estructuras muy sencillas desde un pizarrón táctil, un proyector y una computadora, hasta las estructuras más completas a precios accesibles, como un aula de medios, que le permite realizar video conferencias, evaluaciones en tiempo real y educación a distancia.</li>
    
    <li>Nos permite guardar, compartir e imprimir imágenes al momento de la exposición.</li>
    <li>Manejo de contenidos de manera dinámica y controlada.</li>
    
    </ul>

    <div class="left">
        <img src="/site_media/compu/images/{{ id }}.png">
    </div>
</div>

{% endblock %}

templates/soluciones_tecnologicas/concretar_cita.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
{% block content %}

<script type="text/javascript">
    function submit_aceptar(){
        if( ($("#id_nombre").val() > '') && ($("#id_telefono").val() > '' ) &&  ($("#id_email").val() > '' ) && ($("#id_curriculum").val() > '') ){
            $("#id_aceptar").val("aceptar");
            $("#form_vacante").submit();
        
        } else {
            alert("Es necesario llenar los campos")
        }
        
        

    }

</script>


<div class="fondo_gris_concrete_cita">
    <div class="espacio20" style="width:300px;"></div>
    <div class="cuadro_fondo_gris_titulo" style='font-family:"Trebuchet MS"; margin-left:2px;'>SOLUCIONES TECNOLÓGICAS</div>
        {% espacio 10 %}


      <div id="concrete" >
            <div id="concrete_titulo">CONCIERTE UNA CITA</div>
            <div class="espacio10"></div>
            <form action="." id="form_buscar" method="post" enctype="multipart/form-data">{% csrf_token %}
               <div style="margin-left:5px;">
                    {% espacio 30 %}    
                    <div><div class="tag">{{ form.nombre.label_tag }}:</div> {{ form.nombre }}</div> 
                    {% espacio 16 %}    
                    <div><div class="tag">{{ form.empresa.label_tag }}:</div> {{ form.empresa }}</div> 
                    {% espacio 16 %}    
                    <div><div class="tag">{{ form.telefono.label_tag }}:</div> {{ form.telefono }}</div>  
                    {% espacio 16 %}  
                    <div><div class="tag">{{ form.email.label_tag }}:</div> {{ form.email}}</div>   
                    {% espacio 16 %}  
                    <div>
                        <div style="margin-left:20px; padding-top:3px; font-size:13px;"> 
                            {{ form.comentarios.label_tag }}:
                        </div>
                        {% espacio 6 %}  
                        <div style="margin-left:20px; ">{{ form.comentarios }}</div>
                        {% espacio 10 %} 
                        <input type="submit" value="Enviar" style="margin-left:186px;" />
                     </div>   
                </div>
            </form>
      </div>   
        
      {% if success %}
        <div id="dialog-success">
                <div id="text_dialog_success">
                    Gracias por su interés en nuestra empresa, recibirá una llamada para confirmar cita.
                </div>
        </div>      
        <a href="/concretar_cita/{{ id }}/"><img src="{% static 'site_media/compu/images/x_mensaje.png' %}" alt="" id="cerrar_dialog_success"/></a>
    {% endif %}
    
    
    
    <div class="clear"></div>
<div class="espacio10"></div>
</div>
<script>

    var val ='160px';
    $("#form_buscar").validate();
    $("#id_nombre").css('width', val);
    $("#id_telefono").css('width', val);
    $("#id_empresa").css('width', val);
    $("#id_email").css('width', val);
    $("#id_comentarios").css('width', '215px');
    $("#id_comentarios").css('height', '120px');


    {% if form.errors %}
        var errores = ""
        {% if form.curriculum.errors %} errores += "Curriculum: {{ form.curriculum.errors.0 }} \n"{% endif %}
        {% if form.nombre.errors %} errores += "Nombre: {{ form.nombre.errors.0 }} \n"{% endif %}
        {% if form.telefono.errors %} errores += "Teléfono: {{ form.telefono.errors.0 }} \n"{% endif %}
        {% if form.email.errors %} errores += "Correo Electrónico: {{ form.email.errors.0 }} \n"{% endif %}
        {% if form.puesto.errors %} errores += "Puesto: {{ form.puesto.errors.0 }} \n"{% endif %}
        {% if form.aspiracion.errors %} errores += "Sueldo: {{ form.aspiracion.errors.0 }} \n"{% endif %}
        setTimeout(function(){alert("Se encontraron los siguientes errores:\n" + errores );}, 500);
    {% endif %}


</script>    
{% endblock %}

templates/soluciones_tecnologicas/dynamic_print_routing.html
{% extends "soluciones_tecnologicas/base.html" %}

{% block l_width %}360{% endblock %}

{% block soluciones_title %}
    DYNAMIC PRINT ROUTING
{% endblock %}

{% block soluciones_text %}

<div class="columna_l">
<p class="bold">¿Le interesa la confidencialidad de sus documentos al imprimir y al mismo tiempo apoyar  la ecología?</p>

<p>
Le recomendamos usar una herramienta de software que sirve para hacer “Job Retention” y “Pull Printing” de trabajos de impresión. 

<p>Proporciona confidencialidad en cada una de las impresiones que el usuario realiza, ya que éstas son retenidas y no se imprimen hasta que el mismo usuario se autentifica y realiza el “Pull Printing”. </p>


<p class="beneficios">Beneficios:</p>
        
<ul>
    <li>Autentificación por usuario.</li>
    <li>Confidencialidad de impresiones.</li>
    <li>Reducción de costos de impresión.</li>
    <li>Evitar impresiones olvidadas y duplicadas por el usuario.</li>
    <li>Retención de impresiones.</li>
    <li>Pull Printing directamente en el multifuncional, desde una página Web o con un dispositivo móvil.</li>
</ul>
<div style="text-align:right;" class="demo">Contamos con Demo.</div>
</div>

<div class="columna_r">
    <div class="left">
        <img src="/site_media/compu/images/{{ id }}.png">
    </div>    
</div>

{% endblock %}

templates/soluciones_tecnologicas/hp_bto.html
{% extends "soluciones_tecnologicas/base.html" %}
{% load static %}

{% block l_width %}360{% endblock %}

{% block soluciones_title %}
    HP’ S BUSINESS <br/> TECHNOLOGY OPTIMIZATION (BTO)
{% endblock %}

{% block soluciones_text %}

<div class="columna_l" style="width:310px;">
<p class="bold">¿Desea un estándar mundial de facto en la Gestión de Servicios Informáticos?</p>
<p>La propuesta de valor BTO cuenta con un conjunto de soluciones y servicios que se han diseñado específicamente para identificar problemas en las diferentes áreas de los departamentos de IT, la estrategia, las aplicaciones, las operaciones y la seguridad.</p>

<p class="beneficios">Beneficios:</p>
        
<ul>
    <li>Medición de servicios informáticos.</li>
    <li>Optimiza la infraestructura y automatiza la entrega de los servicios de IT con software basado en ITIL v3.</li>
    <li>Reduce el time to market para ofrecer una ventaja competitiva en el mercado.</li>
    <li>Manejo de calidad de las aplicaciones criticas (soluciones para mitigar el riesgo).</li>
    <li>Gobernabilidad (administración de activos).</li>
    <li>Gestión de la cadena de valor (automatización y mesa de ayuda).</li>
</ul>
</div>

<div class="columna_r">

    <ul>
    <li>Administración de Infraestructura.</li>
    <li>Disminuye costos de IT e incrementa su valor.</li>    
</ul>

    <div class="left">
        <img src="/site_media/compu/images/{{ id }}.png">
    </div>    
</div>

{% endblock %}

templates/soluciones_tecnologicas/hp_data_protector.html
{% extends "soluciones_tecnologicas/base.html" %}

{% block l_width %}360{% endblock %}

{% block soluciones_title %}
    HP DATA PROTECTOR <br />SOFTWARE PARA PC’S.
{% endblock %}

{% block soluciones_text %}

<div class="columna_l">
<p class="bold">¿Sus usuarios han perdido datos de sus lap tops o desktops?</p>
<p class="bold">¿Le ha sido imposible recuperar alguna información de sus usuarios finales?</p>

<p>Entendemos que su información es valiosa y por ende le ofrecemos esta solución que proporciona una copia de seguridad continua y transparente de la información almacenada en los equipos portátiles y de escritorio de una organización, estén o no conectados a la red. </p>

</p>

<p class="beneficios">Beneficios:</p>
<ul>
    <li>Reduce el riesgo asociado con la perdida de datos y protección de PC.</li>
    <li>Reduce el tiempo necesario para administrar respaldos y recuperación por medio de autorización al usuario final.</li>
    <li>Calendarización de respaldos y protección aun fuera de la red.</li>
    <li>Administración centralizada de políticas de respaldos sin riesgo de olvido por parte de un usuario.</li>
    <li>Muestra diversas versiones de sus archivos mediante la consola de recuperación de usuario.</li>
</ul>
<div style="text-align:right;" class="demo">Contamos con Demo.</div>
</div>

<div class="columna_r">
    <div class="left">
        <img src="/site_media/compu/images/{{ id }}.png">
    </div>    
</div>

{% endblock %}